### PR TITLE
Week3

### PR DESCRIPTION
**Pull request by mautoranzo**

### CODE REVIEW

**Review by aschey — APPROVED** [review]
Looks good 👍 Not a big deal, but in the future you can branch off of master for each assignment so you don't have stuff from the previous assignment mixed in with your new PR. Just makes it easier to review.

**Comment by mautoranzo** [comment]
> Looks good 👍 Not a big deal, but in the future you can branch off of master for each assignment so you don't have stuff from the previous assignment mixed in with your new PR. Just makes it easier to review.

**Comment by mautoranzo** [comment]
> Looks good 👍 Not a big deal, but in the future you can branch off of master for each assignment so you don't have stuff from the previous assignment mixed in with your new PR. Just makes it easier to review.

Sorry I am still a new at this, but what you ask is the same to "delete branch"????

**Comment by aschey** [comment]
> > Looks good 👍 Not a big deal, but in the future you can branch off of master for each assignment so you don't have stuff from the previous assignment mixed in with your new PR. Just makes it easier to review.
> 
> Sorry I am still a new at this, but what you ask is the same to "delete branch"????

No, you don't have to delete any branches. Just make sure you're on the master branch when you create any new branches.
```
git checkout master
git checkout -b my-new-branch
```

**Comment by mautoranzo** [comment]
> > > Looks good 👍 Not a big deal, but in the future you can branch off of master for each assignment so you don't have stuff from the previous assignment mixed in with your new PR. Just makes it easier to review.
> > 
> > 
> > Sorry I am still a new at this, but what you ask is the same to "delete branch"????
> 
> No, you don't have to delete any branches. Just make sure you're on the master branch when you create any new branches.
> 
> ```
> git checkout master
> git checkout -b my-new-branch
> ```

Ooooooh ok, now I understand!

**Pull request merged**
